package uz.millygram.protocol

import org.json.JSONObject
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Conformance against the TypeScript implementation.
 *
 * `vectors.json` is generated by `npm run vectors` and must never be edited by
 * hand. If a change to either implementation breaks a test here, the two have
 * diverged and one of them is wrong — that is the entire point of the file.
 */
class ProtocolVectorsTest {

    private val vectors: JSONObject by lazy {
        val stream = checkNotNull(javaClass.classLoader.getResourceAsStream("vectors.json")) {
            "vectors.json is missing; run `npm run vectors` at the repository root"
        }
        JSONObject(stream.bufferedReader().use { it.readText() })
    }

    private fun hex(bytes: ByteArray): String = bytes.joinToString("") { "%02x".format(it) }

    private fun unhex(value: String): ByteArray =
        ByteArray(value.length / 2) { value.substring(it * 2, it * 2 + 2).toInt(16).toByte() }

    @Test
    fun `constants match the reference implementation`() {
        val constants = vectors.getJSONObject("constants")
        assertEquals(constants.getInt("paddedEnvelopeBytes"), Protocol.PADDED_ENVELOPE_BYTES)
        assertEquals(constants.getInt("obliviousRequestBytes"), Protocol.OBLIVIOUS_REQUEST_BYTES)
        assertEquals(constants.getInt("maxPlaintextBytes"), Protocol.MAX_PLAINTEXT_BYTES)
        assertEquals(constants.getString("sigRegister"), Protocol.SIG_REGISTER)
        assertEquals(constants.getString("sigAuth"), Protocol.SIG_AUTH)
        assertEquals(constants.getString("obliviousInfo"), Protocol.OBLIVIOUS_INFO)
    }

    @Test
    fun `base64url encoding matches`() {
        val cases = vectors.getJSONArray("base64url")
        for (index in 0 until cases.length()) {
            val case = cases.getJSONObject(index)
            val bytes = unhex(case.getString("bytesHex"))
            assertEquals(case.getString("encoded"), Protocol.b64(bytes), "encoding case $index")
            assertContentEquals(bytes, Protocol.unb64(case.getString("encoded")), "decoding case $index")
        }
    }

    @Test
    fun `both implementations reject the same non-canonical encodings`() {
        val rejected = vectors.getJSONArray("base64urlRejected")
        assertTrue(rejected.length() > 0, "the vector file must list rejection cases")

        for (index in 0 until rejected.length()) {
            val input = rejected.getString(index)
            assertFailsWith<IllegalArgumentException>(
                "must reject ${input.map { it.code }}; the TypeScript side does",
            ) {
                Protocol.unb64(input)
            }
        }
    }

    @Test
    fun `canonical encoding matches, including the ambiguity guards`() {
        val cases = vectors.getJSONArray("canonical")
        for (index in 0 until cases.length()) {
            val case = cases.getJSONObject(index)
            val parts = case.getJSONArray("parts")

            val decoded = (0 until parts.length()).map { partIndex ->
                val part = parts.getJSONObject(partIndex)
                when (val type = part.getString("type")) {
                    "string" -> Protocol.Part.Text(part.getString("value"))
                    "int" -> Protocol.Part.Integer(part.getLong("value"))
                    else -> error("unknown part type $type")
                }
            }

            assertEquals(
                case.getString("expectedHex"),
                hex(Protocol.canonical(case.getString("tag"), decoded)),
                "canonical case: ${case.getString("name")}",
            )
        }
    }

    @Test
    fun `registration signing payload matches`() {
        val vector = vectors.getJSONObject("registrationSigningPayload")
        val request = vector.getJSONObject("request")

        val payload = Protocol.registrationSigningPayload(
            username = request.getString("username"),
            deviceId = request.getLong("deviceId"),
            registrationId = request.getLong("registrationId"),
            identityKey = Protocol.unb64(request.getString("identityKey")),
            signedPreKeyId = request.getJSONObject("signedPreKey").getLong("keyId"),
            signedPreKeyPublic = Protocol.unb64(request.getJSONObject("signedPreKey").getString("publicKey")),
            kyberPreKeyId = request.getJSONObject("kyberPreKey").getLong("keyId"),
            kyberPreKeyPublic = Protocol.unb64(request.getJSONObject("kyberPreKey").getString("publicKey")),
            timestamp = request.getLong("timestamp"),
        )

        assertEquals(vector.getString("expectedHex"), hex(payload))
    }

    @Test
    fun `auth signing payload matches`() {
        val vector = vectors.getJSONObject("authSigningPayload")
        val payload = Protocol.authSigningPayload(
            aci = vector.getString("aci"),
            deviceId = vector.getLong("deviceId"),
            nonce = unhex(vector.getString("nonceHex")),
        )
        assertEquals(vector.getString("expectedHex"), hex(payload))
    }

    @Test
    fun `padding framing matches and round-trips`() {
        val vector = vectors.getJSONObject("padding")
        val payload = unhex(vector.getString("payloadHex"))
        val padded = Protocol.pad(payload)

        assertEquals(vector.getInt("paddedLength"), padded.size)
        assertEquals(vector.getString("lengthPrefixHex"), hex(padded.copyOfRange(0, 4)))
        assertEquals(
            vector.getString("payloadAtOffset4Hex"),
            hex(padded.copyOfRange(4, 4 + payload.size)),
        )
        assertContentEquals(unhex(vector.getString("roundTripHex")), Protocol.unpad(padded))
    }

    @Test
    fun `proof of work agrees on the same nonces`() {
        val vector = vectors.getJSONObject("proofOfWork")
        val bucketId = vector.getLong("bucketId")
        val content = unhex(vector.getString("contentHex"))
        val difficulty = vector.getInt("difficulty")

        assertTrue(
            Protocol.verifyProofOfWork(bucketId, content, vector.getLong("validNonce"), difficulty),
            "a nonce the reference implementation solved must verify here",
        )
        assertTrue(
            !Protocol.verifyProofOfWork(bucketId, content, vector.getLong("invalidNonce"), difficulty),
            "a nonce the reference implementation rejected must be rejected here",
        )

        // And solving locally must produce something the same verifier accepts.
        val solved = Protocol.solveProofOfWork(bucketId, content, difficulty)
        assertTrue(Protocol.verifyProofOfWork(bucketId, content, solved, difficulty))
    }

    @Test
    fun `a vault sealed by the reference implementation opens here`() {
        val vector = vectors.getJSONObject("vault")
        val key = unhex(vector.getString("keyHex"))
        val aad = vector.getString("aad").toByteArray(Charsets.UTF_8)
        val sealed = unhex(vector.getString("sealedHex"))

        // The vault is per-device and never shared, so nothing was forcing the
        // two implementations to agree on how a value is stored — and they did
        // not. Anything that ever moves one, a backup or an export or a second
        // client, would have found out the hard way.
        val opened = Vault.open(key, aad, sealed)
        assertEquals(vector.getString("plaintextHex"), hex(opened))
    }

    @Test
    fun `registration work matches the reference implementation`() {
        val vector = vectors.getJSONObject("registrationWork")
        val payload = unhex(vector.getString("payloadHex"))
        val difficulty = vector.getInt("difficulty")

        assertTrue(
            Protocol.verifyRegistrationWork(payload, vector.getLong("validNonce"), difficulty),
            "a nonce the reference implementation solved must verify here",
        )
        assertTrue(
            !Protocol.verifyRegistrationWork(payload, vector.getLong("invalidNonce"), difficulty),
            "a nonce the reference implementation rejected must be rejected here",
        )

        val solved = Protocol.solveRegistrationWork(payload, difficulty)
        assertTrue(Protocol.verifyRegistrationWork(payload, solved, difficulty))

        // Domain separation: the two proofs share a hash and must not share a
        // preimage, or a cheap submission proof could be spent as a signup.
        assertTrue(
            !Protocol.verifyProofOfWork(0, payload, vector.getLong("validNonce"), difficulty),
            "registration work must not verify as submission work",
        )
    }

    @Test
    fun `oblivious request layout matches`() {
        val vector = vectors.getJSONObject("obliviousRequest")
        val content = unhex(vector.getString("contentHex"))

        val encoded = Protocol.encodeObliviousRequest(
            vector.getLong("bucketId"),
            vector.getLong("nonce"),
            content,
        )

        assertEquals(vector.getInt("encodedLength"), encoded.size)
        assertEquals(vector.getString("encodedPrefixHex"), hex(encoded.copyOfRange(0, 8)))

        val decoded = checkNotNull(Protocol.decodeObliviousRequest(encoded))
        val expected = vector.getJSONObject("decodesBackTo")
        assertEquals(expected.getLong("bucketId"), decoded.bucketId)
        assertEquals(expected.getLong("nonce"), decoded.nonce)
        assertContentEquals(content, decoded.content)
    }
}

/** Behaviour that is not vector-driven but must still hold. */
class ProtocolInvariantsTest {

    @Test
    fun `padding hides the original length`() {
        val short = "ha".toByteArray()
        val long = "x".repeat(3000).toByteArray()
        assertEquals(Protocol.pad(short).size, Protocol.pad(long).size)
        assertContentEquals(short, Protocol.unpad(Protocol.pad(short)))
        assertContentEquals(long, Protocol.unpad(Protocol.pad(long)))
    }

    @Test
    fun `padding refuses a payload that does not fit`() {
        assertFailsWith<IllegalArgumentException> {
            Protocol.pad(ByteArray(Protocol.PADDED_ENVELOPE_BYTES))
        }
    }

    @Test
    fun `unpadding refuses a wrong-sized or impossible envelope`() {
        assertFailsWith<IllegalArgumentException> { Protocol.unpad(ByteArray(10)) }

        val lying = ByteArray(Protocol.PADDED_ENVELOPE_BYTES)
        lying[0] = 0x7f
        lying[1] = 0xff.toByte()
        assertFailsWith<IllegalArgumentException> { Protocol.unpad(lying) }
    }

    @Test
    fun `a decoded oblivious request rejects anything but the exact size`() {
        assertNull(Protocol.decodeObliviousRequest(ByteArray(Protocol.OBLIVIOUS_REQUEST_BYTES - 1)))
        assertNull(Protocol.decodeObliviousRequest(ByteArray(Protocol.OBLIVIOUS_REQUEST_BYTES + 1)))
    }

    @Test
    fun `proof of work is bound to the bucket it was solved for`() {
        val content = ByteArray(Protocol.PADDED_ENVELOPE_BYTES) { (it % 251).toByte() }
        val nonce = Protocol.solveProofOfWork(3, content, 10)

        assertTrue(Protocol.verifyProofOfWork(3, content, nonce, 10))
        assertTrue(
            !Protocol.verifyProofOfWork(4, content, nonce, 10),
            "work solved for one bucket must not pay for another",
        )
    }

    @Test
    fun `usernames are ascii only`() {
        assertTrue(Protocol.isValidUsername("dilnoza_az"))
        assertTrue(!Protocol.isValidUsername("ab"))
        assertTrue(!Protocol.isValidUsername("Dilnoza"))
        // Cyrillic 'а' rendering as Latin 'a' is exactly the attack this blocks.
        assertTrue(!Protocol.isValidUsername("pаypal"))
    }
}
